#!/usr/bin/python
import sys
import DMPSW
import libDmpAlgTrk as trackAlg 

#-------------------------------------------------------------------
#input file name
seg=len(sys.argv[1])
if seg == 0:
  print 'Usage: ./job inputpath/inputfile'

suffix = 0

for i in range(0,len(sys.argv[1]),1):
	if sys.argv[1][i]=='/':
	   seg=i
	if sys.argv[1][i]=='.':
	   suffix=i
	   
inputpath=sys.argv[1][0:seg]
inputfilename=sys.argv[1][(seg+1):]
inputstem=sys.argv[1][(seg+1):suffix]
#print inputstem
#-------------------------------------------------------------------
#DMPSW.Core.Set("EventNumber","10")
DMPSW.RootIOSvc.Set("Input/Path",inputpath)
DMPSW.RootIOSvc.Set("Input/FileName",inputfilename)
#DMPSW.RootIOSvc.Set("Input/FileName","/Volumes/data/Raw_BgoHits.root")

trkAlg = trackAlg.DmpAlgTrk()
DMPSW.AlgMgr.Append(trkAlg)

DMPSW.Core.Initialize()
#DMPSW.Core.Run()  # you should not use this function in this algrithm
#trkAlg.ProcessEvent(200)   # this for single event
trkAlg.ProcessEvents("200:205")  # this for a set of events, default start from 0 end at the last event
#trkAlg.ProcessEvents("3 10 13 15 205") # this for specific events
DMPSW.Core.Finalize()
