#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpHex2Root, 2014-09-18 21:13:09 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. EQM
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import os
import DMPSW                    # Load DAMPE software
import libDmpHex2Root as Hex2Root

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.Set("EventNumber","4130")     # If NOT set, will use 1234567890
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Error")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.
#DMPSW.Core.Set("LogHeader","On")

#-------------------------------------------------------------------
# RootIOSvc Service
DMPSW.RootIOSvc.Set("Input/Path",os.environ["DMPSWWORK"]+"/run/data/sci")
DMPSW.RootIOSvc.Set("Input/FileName","Raw.frd")
DMPSW.RootIOSvc.Set("Output/Path","./test")
#DMPSW.RootIOSvc.Set("Output/Path",os.environ["DMPSWWORK"]+"/run/data/sci")
DMPSW.RootIOSvc.Set("Output/WriteList","Event/Rdc/EventHeader;Event/Rdc/Bgo")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = Hex2Root.DmpAlgHex2Root()
#rdcAlgBT.Set("Connector/Psd","Psd/EQM")
#rdcAlgBT.Set("Connector/Stk",Stk/EQM")
rdcAlgBT.Set("Connector/Bgo","Bgo/EQM")
#rdcAlgBT.Set("Connector/Nud","Nud/EQM")
#rdcAlgBT.Set("BinaryFile","A2_20140910_123726.frd")
#rdcAlgBT.Set("BinaryFile","A2_20140912_092040.frd")
#rdcAlgBT.Set("BinaryFile","A2_20140910_124351.frd")
#rdcAlgBT.Set("BinaryFile","A2_20140909_183743.frd")
#rdcAlgBT.Set("BinaryFile","test_A2Data00_20140513_191731.frd")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


