/********************************************************************
* ./include/Dictionary_DmpEvtBgoDyCoe.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./include/Dictionary_DmpEvtBgoDyCoe.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary_DmpEvtBgoDyCoe();
extern void G__cpp_setup_inheritanceDictionary_DmpEvtBgoDyCoe();
extern void G__cpp_setup_typetableDictionary_DmpEvtBgoDyCoe();
extern void G__cpp_setup_memvarDictionary_DmpEvtBgoDyCoe();
extern void G__cpp_setup_globalDictionary_DmpEvtBgoDyCoe();
extern void G__cpp_setup_memfuncDictionary_DmpEvtBgoDyCoe();
extern void G__cpp_setup_funcDictionary_DmpEvtBgoDyCoe();
extern void G__set_cpp_environmentDictionary_DmpEvtBgoDyCoe();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmpEvtBgoDyCoe.h"
#include "DmpEvtBgoDyCoe.h~"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_TClass;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_TBuffer;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_TMemberInspector;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_TObject;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_string;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDyCoeLN_DmpEvtBgoDyCoe;

/* STUB derived class for protected member access */
