/********************************************************************
* ./include/Dictionary_DmpEvtBgoDac.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./include/Dictionary_DmpEvtBgoDac.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary_DmpEvtBgoDac();
extern void G__cpp_setup_inheritanceDictionary_DmpEvtBgoDac();
extern void G__cpp_setup_typetableDictionary_DmpEvtBgoDac();
extern void G__cpp_setup_memvarDictionary_DmpEvtBgoDac();
extern void G__cpp_setup_globalDictionary_DmpEvtBgoDac();
extern void G__cpp_setup_memfuncDictionary_DmpEvtBgoDac();
extern void G__cpp_setup_funcDictionary_DmpEvtBgoDac();
extern void G__set_cpp_environmentDictionary_DmpEvtBgoDac();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmpEvtBgoDac.h"
#include "DmpEvtBgoDac.h~"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_TClass;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_TBuffer;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_TMemberInspector;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_TObject;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_string;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoDacLN_DmpEvtBgoDac;

/* STUB derived class for protected member access */
